app/main/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length
from app.models import User

class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=140)])
    submit = SubmitField('Submit')

    #Overload constructor to take and save a new parameter, original_username 
    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username
        
    #custom validator using this original_username
    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')
            
class EmptyForm(FlaskForm):
    submit = SubmitField('Submit')

class PostForm(FlaskForm):
    post = TextAreaField('Say something', validators=[
        DataRequired(), Length(min=1, max=140)])
    submit = SubmitField('Submit')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__,  template_folder='templates')

from app.main import routes

app/main/routes.py
from datetime import datetime
from flask import current_app, g
from flask_login import current_user, login_required
from flask import request, render_template, flash, redirect, url_for
from flask_login import current_user, login_required


from app import db
from app.main.forms import EditProfileForm, EmptyForm, PostForm
from app.models import User, Post
from app.main import bp


@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        posts = current_user.followed_posts().paginate(
            page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
        form = PostForm()
        if form.validate_on_submit():
            post = Post(body=form.post.data, author=current_user)
            db.session.add(post)
            db.session.commit()
            flash('Your post is now live!')
            return redirect(url_for('main.index'))
        return render_template('index.html', title='Home', posts=posts, form=form)
    else: 
        return render_template('index.html', title='Home')

@bp.route('/explore')
@login_required
def explore():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
    return render_template('index.html', title='Explore', posts=posts)

@bp.route('/user/<username>')
@login_required
def user(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()

    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
        page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)

    form = EmptyForm()

    return render_template('user.html', user=user, posts=posts, form=form)

@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', title='Edit Profile',
                           form=form)

@bp.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash(f'User {username} not found.')
            return redirect(url_for('main.index'))
        if user == current_user:
            flash('You cannot follow yourself!')
            return redirect(url_for('main.user', username=username))
        current_user.follow(user)
        db.session.commit()
        flash(f'You are following {username}!')
        return redirect(url_for('main.user', username=username))
    else:
        return redirect(url_for('main.index'))

@bp.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash(f'User {username} not found.')
            return redirect(url_for('main.index'))
        if user == current_user:
            flash('You cannot unfollow yourself!')
            return redirect(url_for('main.user', username=username))
        current_user.unfollow(user)
        db.session.commit()
        flash(f'You are not following {username}.')
        return redirect(url_for('main.user', username=username))
    else:
        return redirect(url_for('main.index'))

app/main/templates/_post.html
<table class="table table-hover table-sm">
    <tr>
        <td width="70px">
            <a href="{{ url_for('main.user', username=post.author.username) }}">
                <img src="{{ post.author.avatar(70) }}" />
            </a>
        </td>
        <td>
            <a href="{{ url_for('main.user', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
            said {{ moment(post.timestamp).fromNow() }}:
            <br>
            {{ post.body }}
        </td>
    </tr>
</table>

app/main/templates/edit_profile.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}

{% block content %}
    <h1>Edit Profile</h1>
    {{ render_form(form) }}
{% endblock %}

app/main/templates/index.html
{% extends "base.html" %}
{% from 'bootstrap5/pagination.html' import render_pagination %}

{% block content %}
{% if current_user.username %}
    <h1>Hi, {{ current_user.username.capitalize() }}!</h1>
    <hr />
    {% if form %}
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.post.label }}<br>
            {{ form.post(cols=32, rows=4) }}<br>
            {% for error in form.post.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
    {% endif %}
    <h3>Recent posts</h3>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}

    {{ render_pagination(posts) }}

{% else %}
    <h1>Hi, unknown user!</h1>
    <h3>Log in to see posts..</h3>
{% endif %}
{% endblock %}

app/main/templates/user.html
{% extends "base.html" %}
{% from 'bootstrap5/pagination.html' import render_pagination %}

{% block content %}
    <table>
        <tr valign="top">
            <td><img src="{{ user.avatar(128) }}"></td>
            <td>
                <h1>User: {{ user.username }}</h1>
                <p>Email: {{ user.email }}</p>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                    <p>Last seen on: {{ moment(user.last_seen).format('LLL') }}</p>
                {% endif %}
            </td>
        </tr>
    </table>
    {% if user == current_user %}
        <p><a href="{{ url_for('main.edit_profile') }}">Edit your profile</a></p>
    {% elif not current_user.is_following(user) %}
    <p>
        <form action="{{ url_for('main.follow', username=user.username) }}" method="post">
            {{ form.hidden_tag() }}
            {{ form.submit(value='Follow') }}
        </form>
    </p>
    {% else %}
    <p>
        <form action="{{ url_for('main.unfollow', username=user.username) }}" method="post">
            {{ form.hidden_tag() }}
            {{ form.submit(value='Unfollow') }}
        </form>
    </p>
    {% endif %}
    <hr>
    <h3>{{ user.username.capitalize() }}s posts:</h3>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    {{ render_pagination(posts) }}
{% endblock %}